import React, { useState } from 'react';

export default function App() {
  const [activeTab, setActiveTab] = useState('catalog');

  return (
    <div className="min-h-screen bg-slate-900 text-white p-6 font-sans">
      <header className="max-w-6xl mx-auto border-b border-slate-700 pb-4 mb-6 flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold text-indigo-400">Library Management System</h1>
          <p className="text-xs text-slate-400">Django REST + React Multi-Agent Architecture</p>
        </div>
        <nav className="flex space-x-2">
          {['catalog', 'loans', 'auth', 'admin'].map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`px-4 py-2 text-xs font-semibold rounded-lg capitalize transition-all ${
                activeTab === tab ? 'bg-indigo-600 text-white' : 'bg-slate-800 text-slate-400 hover:text-white'
              }`}
            >
              {tab}
            </button>
          ))}
        </nav>
      </header>
      <main className="max-w-6xl mx-auto">
        <div className="bg-slate-800 p-6 rounded-xl border border-slate-700">
          <h2 className="text-lg font-semibold text-indigo-300 capitalize mb-2">{activeTab} Module Active</h2>
          <p className="text-sm text-slate-300">Generated by assigned worker agents under Django REST API & React framework.</p>
        </div>
      </main>
    </div>
  );
}
